function(add_main_executable_file TARGET_NAME SOURCE_FILE)
    if(ARGC GREATER 2)
        message(FATAL_ERROR "add_main_executable_file expects exactly one SOURCE_FILE, not ${ARGN}")
    endif()

    set(ARG_MODE "none")
    get_filename_component(SRC_PATH "${CMAKE_CURRENT_SOURCE_DIR}/${SOURCE_FILE}" REALPATH)
    if(NOT EXISTS "${SRC_PATH}")
        message(FATAL_ERROR "add_main_executable_file: SOURCE_FILE='${SOURCE_FILE}' does not exist at '${SRC_PATH}'")
    endif()
    file(READ "${SRC_PATH}" SOURCE_CONTENT)

    set(ENTRY_POINT "main")
    set(IS_GUI false)

    if(SOURCE_CONTENT MATCHES [[WinMain\s*\(\s*HINSTANCE\s*,\s*HINSTANCE\s*,\s*PSTR\s*,\s*int\s*\)]])
        set(ENTRY_POINT "WinMain")
        set(IS_GUI true)
    elseif(SOURCE_CONTENT MATCHES [[WinMain\s*\(\s*HINSTANCE\s+hInstance\s*,\s*HINSTANCE\s+hPrevInstance\s*,\s*PSTR\s+lpCmdLine\s*,\s*int\s+nCmdShow\s*\)]])
        set(ENTRY_POINT "WinMain")
        set(IS_GUI true)
    elseif(SOURCE_CONTENT MATCHES [[wWinMain\s*\(\s*HINSTANCE\s*,\s*HINSTANCE\s*,\s*PWSTR\s*,\s*int\s*\)]])
        set(ENTRY_POINT "wWinMain")
        set(IS_GUI true)
    elseif(SOURCE_CONTENT MATCHES [[wWinMain\s*\(\s*HINSTANCE\s+hInstance\s*,\s*HINSTANCE\s+hPrevInstance\s*,\s*PWSTR\s+pCmdLine\s*,\s*int\s+nCmdShow\s*\)]])
        set(ENTRY_POINT "wWinMain")
        set(IS_GUI true)
    elseif(SOURCE_CONTENT MATCHES [[_tmain\s*\(\s*int\s+argc\s*,\s*_TCHAR\s*[*]\s*[*]argv\s*\)]])
        set(ARG_MODE "argc_argv")
    elseif(SOURCE_CONTENT MATCHES [[_wmain\s*\(\s*int\s+argc\s*,\s*wchar_t\s*[*]\s*[*]argv\s*\)]])
        set(ARG_MODE "argc_argv")
    elseif(SOURCE_CONTENT MATCHES [[_tWinMain\s*\(\s*HINSTANCE\s*,\s*HINSTANCE\s*,\s*LPTSTR\s*,\s*int\s*\)]])
        set(ENTRY_POINT "_tWinMain")
        set(IS_GUI true)
    elseif(SOURCE_CONTENT MATCHES [[int\s+main\s*\(\s*void\s*\)]])
        set(ARG_MODE "none")
    elseif(SOURCE_CONTENT MATCHES [[int\s+main\s*\(\s*int\s+argc\s*,\s*char\s*[*][*]\s*argv\s*\)]])
        set(ARG_MODE "argc_argv")
    elseif(SOURCE_CONTENT MATCHES [[int\s+main\s*\(\s*int\s+argc\s*,\s*char\s*\*\s*argv\s*\[\s*\]\s*\)]])
        set(ARG_MODE "argc_argv")
    elseif(SOURCE_CONTENT MATCHES [[int\s+main\s*\(\s*int\s+argc\s*,\s*char\s*[*][*]\s*argv\s*,\s*char\s*[*][*]\s*envp\s*\)]])
        set(ARG_MODE "argc_argv_envp")
    elseif(SOURCE_CONTENT MATCHES [[void\s+main\s*\(\s*void\s*\)]])
        set(ARG_MODE "none")
    elseif(SOURCE_CONTENT MATCHES [[void\s+main\s*\(\s*int\s+argc\s*,\s*char\s*[*][*]\s*argv\s*\)]])
        set(ARG_MODE "argc_argv")
    endif()

    if(ENTRY_POINT STREQUAL "main")
        set(RENAMED_MAIN "user_main")
        if(ARG_MODE STREQUAL "none")
            set(WRAPPER_MAIN_SIGNATURE "int main()")
            set(WRAPPER_MAIN_ARGS)
            set(WRAPPER_MAIN_CALL "user_main()")
        elseif(ARG_MODE STREQUAL "argc_argv")
            set(WRAPPER_MAIN_SIGNATURE "int main(int argc, char *argv[])")
            set(WRAPPER_MAIN_ARGS "argc, argv")
            set(WRAPPER_MAIN_CALL "user_main(argc, argv)")
        elseif(ARG_MODE STREQUAL "argc_argv_envp")
            set(WRAPPER_MAIN_SIGNATURE "int main(int argc, char *argv[], char *envp[])")
            set(WRAPPER_MAIN_ARGS "argc, argv, envp")
            set(WRAPPER_MAIN_CALL "user_main(argc, argv, envp)")
        else()
            message(FATAL_ERROR "add_main_executable_file: could not recognize main() signature in '${SOURCE_FILE}'")
        endif()
        set(WRAPPER_MAIN_BODY "InstallFileInterceptionHooks();\nreturn ${WRAPPER_MAIN_CALL};")
    elseif(ENTRY_POINT STREQUAL "WinMain")
        set(RENAMED_MAIN "user_WinMain")
        set(WRAPPER_MAIN_SIGNATURE "int WINAPI ${RENAMED_MAIN}(HINSTANCE hInstance, HINSTANCE hPrevInstance, PSTR lpCmdLine, int nCmdShow)")
        set(WRAPPER_MAIN_BODY [=[
    InstallFileInterceptionHooks();
    return user_WinMain(hInstance, hPrevInstance, lpCmdLine, nCmdShow);
]=])
    elseif(ENTRY_POINT STREQUAL "wWinMain")
        set(RENAMED_MAIN "user_wWinMain")
        set(WRAPPER_MAIN_SIGNATURE "int WINAPI ${RENAMED_MAIN}(HINSTANCE hInstance, HINSTANCE hPrevInstance, PWSTR pCmdLine, int nCmdShow)")
        set(WRAPPER_MAIN_BODY [=[
    InstallFileInterceptionHooks();
    return user_wWinMain(hInstance, hPrevInstance, pCmdLine, nCmdShow);
]=])
    elseif(ENTRY_POINT STREQUAL "_tWinMain")
        set(RENAMED_MAIN "user_tWinMain")
        set(WRAPPER_MAIN_SIGNATURE "int WINAPI ${RENAMED_MAIN}(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPTSTR lpCmdLine, int nCmdShow)")
        set(WRAPPER_MAIN_BODY [=[
    InstallFileInterceptionHooks();
    return user_tWinMain(hInstance, hPrevInstance, lpCmdLine, nCmdShow);
]=])
    endif()

    set(WRAPPER_MAIN "${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}_wrapper_main.cpp")
    file(WRITE "${WRAPPER_MAIN}" "// Auto-generated wrapper main\n")
    file(APPEND "${WRAPPER_MAIN}" "#define ${ENTRY_POINT} ${RENAMED_MAIN}\n")
    file(APPEND "${WRAPPER_MAIN}" "#include \"${SRC_PATH}\"\n")
    file(APPEND "${WRAPPER_MAIN}" "#undef ${ENTRY_POINT}\n")
    file(APPEND "${WRAPPER_MAIN}" "extern \"C\" void InstallFileInterceptionHooks();\n")
    file(APPEND "${WRAPPER_MAIN}" "${WRAPPER_MAIN_SIGNATURE}\n{\n")
    file(APPEND "${WRAPPER_MAIN}" "    ${WRAPPER_MAIN_BODY}\n")
    file(APPEND "${WRAPPER_MAIN}" "}\n")

    get_target_property(TGT_SOURCES ${TARGET_NAME} SOURCES)
    set(NEW_SOURCES "")
    foreach(src ${TGT_SOURCES})
        get_filename_component(ABS_SRC "${src}" ABSOLUTE)
        if(NOT ABS_SRC STREQUAL "${SRC_PATH}")
            list(APPEND NEW_SOURCES "${src}")
        endif()
    endforeach()
    set_target_properties(${TARGET_NAME} PROPERTIES SOURCES "${NEW_SOURCES}")
    target_sources(${TARGET_NAME} PRIVATE "${WRAPPER_MAIN}")

    if((ENTRY_POINT STREQUAL "WinMain" OR ENTRY_POINT STREQUAL "wWinMain" OR ENTRY_POINT STREQUAL "_tWinMain") AND WIN32)
        set_property(TARGET ${TARGET_NAME} PROPERTY WIN32_EXECUTABLE TRUE)
    endif()

    target_link_libraries(${TARGET_NAME} PRIVATE CMakeFileEmbedder::CMakeFileEmbedder)
endfunction()